# Generated by Django 5.2.12 on 2026-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('United States', 'United States'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Singapore', 'Singapore'), ('Hong Kong', 'Hong Kong')], max_length=50)),
                ('product', models.CharField(choices=[('Fiber Internet 300 Mbps', 'Fiber Internet 300 Mbps'), ('5GUnlimited Mobile Plan', '5GUnlimited Mobile Plan'), ('Fiber Internet 1 Gbps', 'Fiber Internet 1 Gbps'), ('Business Internet 500 Mbps', 'Business Internet 500 Mbps'), ('VoIP Corporate Package', 'VoIP Corporate Package')], max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_by', models.CharField(choices=[('Mr. Michael Harris', 'Mr. Michael Harris'), ('Mr. Ryan Cooper', 'Mr. Ryan Cooper'), ('Ms. Olivia Carter', 'Ms. Olivia Carter'), ('Mr. Lucas Martin', 'Mr. Lucas Martin')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
