# Generated by Django 5.2.12 on 2026-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('United States', 'United States'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Singapore', 'Singapore'), ('Hong Kong', 'Hong Kong')], max_length=50),
        ),
    ]
