# Generated by Django 5.2.12 on 2026-03-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardConfig',
            new_name='Dashboard',
        ),
    ]
